default_context:
  project_name: 'guc-web-app'
  project_slug: 'guc-web-app'
  domain_main: 'guc-web-app.com'
  domain_staging: 'stag.guc-web-app.com'
  docker_swarm_stack_name_main: 'guc-web-app'
  docker_swarm_stack_name_staging: 'stag-guc-web-app'
  secret_key: 'changethis'
  first_superuser: 'admin@guc-web-app.com'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.guc-web-app.com", "https://stag.guc-web-app.com", "https://guc-web-app.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@guc-web-app.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'admin@guc-web-app.com'
  pgadmin_default_user_password: 'postgres'
  traefik_constraint_tag: 'guc-web-app.com'
  traefik_constraint_tag_staging: 'stag.guc-web-app.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: 'guc'
  docker_image_backend: 'guc-backend'
  docker_image_celeryworker: 'guc-celeryworker'
  docker_image_frontend: 'guc-frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
